[package]
name = "srl_bot"
version = "0.1.0"
authors = ["memoryleak47 <memoryleak47@protonmail.ch>"]

[dependencies]
libsrl = { path = "../libsrl" }
rand = "0.3"
serde = "*"
serde_derive = "*"
serde_json = "*"
